/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[appId]': RouteRecordInfo<'/[appId]', '/:appId', { appId: ParamValue<true> }, { appId: ParamValue<false> }>,
    '/[appId]/[qualifiedName]/': RouteRecordInfo<'/[appId]/[qualifiedName]/', '/:appId/:qualifiedName', { appId: ParamValue<true>, qualifiedName: ParamValue<true> }, { appId: ParamValue<false>, qualifiedName: ParamValue<false> }>,
    '/[appId]/[qualifiedName]/[objectId]/': RouteRecordInfo<'/[appId]/[qualifiedName]/[objectId]/', '/:appId/:qualifiedName/:objectId', { appId: ParamValue<true>, qualifiedName: ParamValue<true>, objectId: ParamValue<true> }, { appId: ParamValue<false>, qualifiedName: ParamValue<false>, objectId: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
